// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: reader.proto

package pbreader

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EthClient is the client API for Eth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EthClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (Eth_GetClient, error)
}

type ethClient struct {
	cc grpc.ClientConnInterface
}

func NewEthClient(cc grpc.ClientConnInterface) EthClient {
	return &ethClient{cc}
}

func (c *ethClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (Eth_GetClient, error) {
	stream, err := c.cc.NewStream(ctx, &Eth_ServiceDesc.Streams[0], "/sf.reader.v1.Eth/Get", opts...)
	if err != nil {
		return nil, err
	}
	x := &ethGetClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Eth_GetClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type ethGetClient struct {
	grpc.ClientStream
}

func (x *ethGetClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EthServer is the server API for Eth service.
// All implementations must embed UnimplementedEthServer
// for forward compatibility
type EthServer interface {
	Get(*Request, Eth_GetServer) error
	mustEmbedUnimplementedEthServer()
}

// UnimplementedEthServer must be embedded to have forward compatible implementations.
type UnimplementedEthServer struct {
}

func (UnimplementedEthServer) Get(*Request, Eth_GetServer) error {
	return status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEthServer) mustEmbedUnimplementedEthServer() {}

// UnsafeEthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EthServer will
// result in compilation errors.
type UnsafeEthServer interface {
	mustEmbedUnimplementedEthServer()
}

func RegisterEthServer(s grpc.ServiceRegistrar, srv EthServer) {
	s.RegisterService(&Eth_ServiceDesc, srv)
}

func _Eth_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EthServer).Get(m, &ethGetServer{stream})
}

type Eth_GetServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type ethGetServer struct {
	grpc.ServerStream
}

func (x *ethGetServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// Eth_ServiceDesc is the grpc.ServiceDesc for Eth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Eth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.reader.v1.Eth",
	HandlerType: (*EthServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Get",
			Handler:       _Eth_Get_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "reader.proto",
}
