// @generated by protoc-gen-connect-web v0.8.4 with parameter "target=ts"
// @generated from file proto/service.proto (package eth.service.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetBlockInfoRequest, GetMonthRequest, GetYearRequest, Month, Months } from "./service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service eth.service.v1.BlockMeta
 */
export const BlockMeta = {
  typeName: "eth.service.v1.BlockMeta",
  methods: {
    /**
     * @generated from rpc eth.service.v1.BlockMeta.GetBlockInfo
     */
    getBlockInfo: {
      name: "GetBlockInfo",
      I: GetBlockInfoRequest,
      O: Months,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc eth.service.v1.BlockMeta.GetMonth
     */
    getMonth: {
      name: "GetMonth",
      I: GetMonthRequest,
      O: Month,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc eth.service.v1.BlockMeta.GetYear
     */
    getYear: {
      name: "GetYear",
      I: GetYearRequest,
      O: Months,
      kind: MethodKind.Unary,
    },
  }
} as const;

